language: elixir

matrix:
  include:
    - otp_release: 21.0
      elixir: 1.6.6

sudo: false

cache:
  directories:
    - _build
    - deps

script:
  - mix credo
  - mix format --check-formatted
  - mix dialyzer --halt-exit-status
  - mix test
